export const mobile_data = [
    {
        "product_img": "https://m.media-amazon.com/images/I/81T3olLXpUL._SX679_.jpg",
        "product_name": "Samsung Galaxy M05",
        "brand": "Samsung",
        "ram": 4,
        "storage": 64,
        "battery": 5000,
        "Price": 6999,
        "screen_size": 6.7,
        "camera": 50,
        "description": "An affordable smartphone with powerful performance and a long-lasting battery.",
        "operating_system": "Android 12",
        "processor": "MediaTek Helio G85"
    },
    {
        "product_img": "https://m.media-amazon.com/images/I/81scQ7qlPuL._SX679_.jpg",
        "product_name": "Samsung Galaxy M15",
        "brand": "Samsung",
        "ram": 6,
        "storage": 128,
        "battery": 6000,
        "Price": 13499,
        "screen_size": 6.5,
        "camera": 50,
        "description": "A mid-range phone with impressive storage and a huge battery capacity.",
        "operating_system": "Android 13",
        "processor": "Exynos 850"
    },
    {
        "product_img": "https://m.media-amazon.com/images/I/81FZk5pGzFL._SX679_.jpg",
        "product_name": "Samsung Galaxy M35 5G",
        "brand": "Samsung",
        "ram": 8,
        "storage": 256,
        "battery": 6000,
        "Price": 23499,
        "screen_size": 6.6,
        "camera": 50,
        "description": "A 5G-ready smartphone with ample storage and cutting-edge features.",
        "operating_system": "Android 13",
        "processor": "Qualcomm Snapdragon 695"
    },
    {
        "product_img": "https://m.media-amazon.com/images/I/81NRD3LJJEL._SX679_.jpg",
        "product_name": "Samsung Galaxy A14",
        "brand": "Samsung",
        "ram": 4,
        "storage": 128,
        "battery": 5000,
        "Price": 12449,
        "screen_size": 6.6,
        "camera": 50,
        "description": "An elegant phone offering advanced features and seamless performance.",
        "operating_system": "Android 13",
        "processor": "Exynos 850"
    },
    {
        "product_img": "https://m.media-amazon.com/images/I/913EiorAS0L._SL1500_.jpg",
        "product_name": "Samsung Galaxy M14",
        "brand": "Samsung",
        "ram": 4,
        "storage": 64,
        "battery": 5000,
        "Price": 8279,
        "screen_size": 6.7,
        "camera": 50,
        "description": "A value-for-money smartphone with a focus on display and battery life.",
        "operating_system": "Android 13",
        "processor": "Exynos 1330"
    },
    {
        "product_img": "https://m.media-amazon.com/images/I/81Xl10tx7hL._SX679_.jpg",
        "product_name": "OPPO A3 5G",
        "brand": "Oppo",
        "ram": 6,
        "storage": 128,
        "battery": 5100,
        "Price": 15999,
        "screen_size": 6.7,
        "camera": 50,
        "description": "A sleek and stylish phone offering 5G connectivity and excellent performance.",
        "operating_system": "ColorOS 12.1 (Based on Android 12)",
        "processor": "Qualcomm Snapdragon 695"
    },
    {
        "product_img": "https://m.media-amazon.com/images/I/81CFCXH1tVL._SX679_.jpg",
        "product_name": "OPPO F27 5G",
        "brand": "Oppo",
        "ram": 8,
        "storage": 128,
        "battery": 5000,
        "Price": 20999,
        "screen_size": 6.67,
        "camera": 50,
        "description": "A premium 5G smartphone designed for performance and aesthetics.",
        "operating_system": "ColorOS 13 (Based on Android 13)",
        "processor": "MediaTek Dimensity 7200"
    },
    {
        "product_img": "https://m.media-amazon.com/images/I/81SmCFYGRlL._SX679_.jpg",
        "product_name": "OPPO A3X 4G",
        "brand": "Oppo",
        "ram": 4,
        "storage": 64,
        "battery": 5100,
        "Price": 8999,
        "screen_size": 6.67,
        "camera": 50,
        "description": "An entry-level smartphone with reliable performance and a robust battery.",
        "operating_system": "ColorOS 12.1 (Based on Android 12)",
        "processor": "Unisoc T616"
    },
    {
        "product_img": "https://m.media-amazon.com/images/I/81Tx+kozw2L._SX679_.jpg",
        "product_name": "OPPO A3X 5G",
        "brand": "Oppo",
        "ram": 4,
        "storage": 64,
        "battery": 5100,
        "Price": 12499,
        "screen_size": 6.67,
        "camera": 8,
        "description": "Affordable 5G smartphone for everyday multitasking and connectivity.",
        "operating_system": "ColorOS 12 (Based on Android 12)",
        "processor": "Qualcomm Snapdragon 480 5G"
    },
    {
        "product_img": "https://m.media-amazon.com/images/I/81Tx+kozw2L._SX679_.jpg",
        "product_name": "OPPO A3X 5G",
        "brand": "Oppo",
        "ram": 4,
        "storage": 128,
        "battery": 5100,
        "Price": 13499,
        "screen_size": 6.67,
        "camera": 8,
        "description": "Enhanced 5G model with more storage for all your needs.",
        "operating_system": "ColorOS 12 (Based on Android 12)",
        "processor": "Qualcomm Snapdragon 480 5G"
    },
    {
        "product_img": "https://m.media-amazon.com/images/I/81Tx+kozw2L._SX679_.jpg",
        "product_name": "OPPO A3X 5G",
        "brand": "Oppo",
        "ram": 4,
        "storage": 128,
        "battery": 5100,
        "Price": 13499,
        "screen_size": 6.67,
        "camera": 8,
        "description": "Oppo A3X 5G smartphone with a 6.67-inch display, 4GB RAM, and 128GB storage. Features a 5100mAh battery and an 8MP camera for a smooth and efficient experience.",
        "operating_system": "ColorOS 12 (Based on Android 12)",
        "processor": "Qualcomm Snapdragon 480 5G"
    },
    {
        "product_img": "https://m.media-amazon.com/images/I/71NnrsYP63L._SX679_.jpg",
        "product_name": "Redmi Note 13",
        "brand": "Redmi",
        "ram": 6,
        "storage": 128,
        "battery": 5000,
        "Price": 15999,
        "screen_size": 6.67,
        "camera": 108,
        "description": "Redmi Note 13 offers a stunning 108MP camera, 6.67-inch screen, 6GB RAM, and 128GB storage for a premium experience at an affordable price.",
        "operating_system": "MIUI 14 (Based on Android 13)",
        "processor": "MediaTek Dimensity 1080"
    },
    {
        "product_img": "https://m.media-amazon.com/images/I/81nMsYgIHdL._SX679_.jpg",
        "product_name": "Redmi 13C",
        "brand": "Redmi",
        "ram": 4,
        "storage": 128,
        "battery": 5000,
        "Price": 9199,
        "screen_size": 6.74,
        "camera": 50,
        "description": "Redmi 13C features a 50MP camera, a large 6.74-inch display, 4GB RAM, and 128GB storage. Perfect for budget-friendly users.",
        "operating_system": "MIUI 13 (Based on Android 12)",
        "processor": "Unisoc T612"
    },
    {
        "product_img": "https://m.media-amazon.com/images/I/71r0Ysx+oVL._SX679_.jpg",
        "product_name": "realme NARZO N61",
        "brand": "Realme",
        "ram": 4,
        "storage": 64,
        "battery": 5000,
        "Price": 7489,
        "screen_size": 6.75,
        "camera": 8,
        "description": "Realme Narzo N61 comes with a 6.75-inch display, 5000mAh battery, 4GB RAM, and 64GB storage for efficient multitasking.",
        "operating_system": "Realme UI 3.0 (Based on Android 12)",
        "processor": "Unisoc T616"
    },
    {
        "product_img": "https://m.media-amazon.com/images/I/71Qwha+BcbL._SX679_.jpg",
        "product_name": "realme NARZO 70 Pro",
        "brand": "Realme",
        "ram": 8,
        "storage": 256,
        "battery": 5000,
        "Price": 16998,
        "screen_size": 6.67,
        "camera": 50,
        "description": "Realme Narzo 70 Pro with an 8GB RAM, 256GB storage, 50MP camera, and 5000mAh battery for professional performance.",
        "operating_system": "Realme UI 4.0 (Based on Android 13)",
        "processor": "MediaTek Dimensity 7050"
    },
    
    {
        "product_img": "https://m.media-amazon.com/images/I/51CG+lXrQIL._SX679_.jpg",
        "product_name": "Vivo T3X 5G",
        "brand": "Vivo",
        "ram": 4,
        "storage": 128,
        "battery": 5000,
        "Price": 12870,
        "screen_size": 6.72,
        "camera": 64,
        "description": "Vivo T3X 5G offers a balanced mix of performance with a 64MP camera, 5000mAh battery, and 128GB storage.",
        "operating_system": "Android 13",
        "processor": "Qualcomm Snapdragon 695"
    },
    {
        "product_img": "https://m.media-amazon.com/images/I/61Gl4860bcL._SX679_.jpg",
        "product_name": "Motorola All-New A10",
        "brand": "Moto",
        "ram": 0.03,
        "storage": 32,
        "battery": 800,
        "Price": 1209,
        "screen_size": 2.5,
        "camera": 2,
        "description": "The Motorola All-New A10 is a compact and affordable phone with 32MB storage and a 2.5-inch display, perfect for basic communication needs.",
        "operating_system": "Feature OS",
        "processor": "Single-core Processor"
    },
    {
        "product_img": "https://m.media-amazon.com/images/I/71zoUhd6fXL._SX679_.jpg",
        "product_name": "Moto G85",
        "brand": "Moto",
        "ram": 8,
        "storage": 128,
        "battery": 5000,
        "Price": 19500,
        "screen_size": 6.67,
        "camera": 50,
        "description": "The Moto G85 combines power and performance with 8GB RAM, 128GB storage, and a 50MP camera. Its 6.67-inch display and 5000mAh battery make it ideal for multitasking.",
        "operating_system": "Android 12",
        "processor": "MediaTek Helio G85"
    },
    {
        "product_img": "https://m.media-amazon.com/images/I/81dl4dQY3BL._SX569_.jpg",
        "product_name": "Motorola G45",
        "brand": "Moto",
        "ram": 4,
        "storage": 128,
        "battery": 5000,
        "Price": 11834,
        "screen_size": 6.5,
        "camera": 50,
        "description": "The Motorola G45 offers 4GB RAM, 128GB storage, and a 50MP camera, providing a reliable option for everyday use at an affordable price.",
        "operating_system": "Android 12",
        "processor": "Qualcomm Snapdragon 680"
    },
    {
        "product_img": "https://m.media-amazon.com/images/I/61lLjrvDEkL._SX679_.jpg",
        "product_name": "Apple iPhone 16 (128 GB) - White",
        "brand": "Apple",
        "ram": 128,
        "storage": 128,
        "battery": 5000,
        "Price": 77990,
        "screen_size": 6.1,
        "camera": 108,
        "description": "The Apple iPhone 16 combines premium features, including a 108MP camera, 6.1-inch display, and 128GB storage, delivering exceptional performance and design.",
        "operating_system": "iOS 16",
        "processor": "A16 Bionic chip"
    },
    {
        "product_img": "https://m.media-amazon.com/images/I/61bK6PMOC3L._SX679_.jpg",
        "product_name": "Apple iPhone 14 (128 GB) - Blue",
        "brand": "Apple",
        "ram": 128,
        "storage": 128,
        "battery": 5000,
        "Price": 54900,
        "screen_size": 6.1,
        "camera": 64,
        "description": "The Apple iPhone 14 features a sleek design, 64MP camera, 128GB storage, and a 6.1-inch display for immersive viewing experiences.",
        "operating_system": "iOS 16",
        "processor": "A15 Bionic chip"
    },
    {
        "product_img": "https://m.media-amazon.com/images/I/71GLMJ7TQiL._SX679_.jpg",
        "product_name": "Apple iPhone 13 (128GB) - Starlight",
        "brand": "Apple",
        "ram": 8,
        "storage": 128,
        "battery": 5000,
        "Price": 45499,
        "screen_size": 6.1,
        "camera": 12,
        "description": "The Apple iPhone 13 combines a stylish design with powerful performance, featuring a 12MP camera, 8GB RAM, and 128GB storage.",
        "operating_system": "iOS 15",
        "processor": "A15 Bionic chip"
    },
    {
        "product_img": "https://m.media-amazon.com/images/I/61VuVU94RnL._SX679_.jpg",
        "product_name": "Apple iPhone 13 (128GB) - Midnight",
        "brand": "Apple",
        "ram": 8,
        "storage": 128,
        "battery": 5100,
        "Price": 45499,
        "screen_size": 6.1,
        "camera": 12,
        "description": "The Apple iPhone 13 Midnight edition offers a 12MP camera, 6.1-inch display, and 5100mAh battery, delivering reliable performance and premium design.",
        "operating_system": "iOS 15",
        "processor": "A15 Bionic chip"
    },
    {
        "product_img": "https://m.media-amazon.com/images/I/615O-NFQKdL._SX679_.jpg",
        "product_name": "Apple iPhone 16 (128 GB) - Black",
        "brand": "Apple",
        "ram": 128,
        "storage": 128,
        "battery": 5000,
        "Price": 78400,
        "screen_size": 6.1,
        "camera": 48,
        "description": "The Apple iPhone 16 Black offers a 48MP camera, 128GB storage, and a 6.1-inch display for unmatched user experiences.",
        "operating_system": "iOS 16",
        "processor": "A16 Bionic chip"
    },
    {
        "product_img": "https://m.media-amazon.com/images/I/71d7rfSl0wL._SX679_.jpg",
        "product_name": "Apple iPhone 15 (128 GB) - Blue",
        "brand": "Apple",
        "ram": 8,
        "storage": 128,
        "battery": 5000,
        "Price": 65900,
        "screen_size": 6.1,
        "camera": 48,
        "description": "The Apple iPhone 15 features an impressive 48MP camera, 6.1-inch display, and 128GB storage for exceptional performance and style.",
        "operating_system": "iOS 17",
        "processor": "A17 Pro chip"
    },
    {
        "product_img": "https://m.media-amazon.com/images/I/719LcA76E5L._SX679_.jpg",
        "product_name": "POCO M6 5G, Orion Blue (4GB, 64GB)",
        "brand": "Poco",
        "ram": 4,
        "storage": 64,
        "battery": 5000,
        "Price": 7999,
        "screen_size": 17.12,
        "camera": 50,
        "description": "The POCO M6 5G features a 50MP camera, 4GB RAM, and 64GB storage, offering excellent value with a massive display for entertainment.",
        "operating_system": "MIUI 13 (based on Android 12)",
        "processor": "MediaTek Dimensity 700"
    },
    {
        "product_img": "https://m.media-amazon.com/images/I/71jWhIexDHL._SL1500_.jpg",
        "product_name": "POCO C61 Diamond Dust Black 4GB RAM 64GB ROM",
        "brand": "Poco",
        "ram": 4,
        "storage": 64,
        "battery": 5000,
        "Price": 6299,
        "screen_size": 17.4,
        "camera": 8,
        "description": "The POCO C61 Diamond Dust Black is a budget-friendly device with a durable design, featuring 4GB RAM, 64GB storage, and a reliable 8MP camera.",
        "operating_system": "MIUI 12 (based on Android 10)",
        "processor": "MediaTek Helio G35"
    },
    {
        "product_img": "https://m.media-amazon.com/images/I/71WRGTt11fL._SX679_.jpg",
        "product_name": "POCO X5 5G",
        "brand": "Poco",
        "ram": 6,
        "storage": 128,
        "battery": 5000,
        "Price": 18999,
        "screen_size": 6.67,
        "camera": 48,
        "description": "POCO X5 5G delivers 5G performance with 6GB RAM, 128GB storage, and a 48MP camera, perfect for multitasking and photography.",
        "operating_system": "MIUI 14 (based on Android 12)",
        "processor": "Qualcomm Snapdragon 695"
    },
    {
        "product_img": "https://m.media-amazon.com/images/I/71HFzPLXyLL._SX679_.jpg",
        "product_name": "Samsung Galaxy A05s",
        "brand": "Samsung",
        "ram": 4,
        "storage": 128,
        "battery": 5000,
        "Price": 13990,
        "screen_size": 6.5,
        "camera": 50,
        "description": "The Samsung Galaxy A05s offers 4GB RAM, 128GB storage, and a 50MP camera for a balanced and affordable smartphone experience.",
        "operating_system": "One UI 5 (based on Android 13)",
        "processor": "Qualcomm Snapdragon 680"
    }




];


