export const laptop_data = [
  {
      "product_img": "https://m.media-amazon.com/images/I/61fX7JMM3-L._SX679_.jpg",
      "product_name": "Dell 15 Thin & Light Laptop, Core i5-1235U Processor",
      "brand": "Dell",
      "ram": 8,
      "Price": 43990,
      "description": "The Dell 15 Thin & Light Laptop is powered by the Intel Core i5-1235U processor and 8GB RAM, offering a balanced performance for multitasking. Its lightweight design makes it ideal for work on the go.",
      "storage": 512,
      "battery": 4200,
      "screen_size": 15.6,
      "operating_system": "Windows 11",
      "processor": "Intel Core i5-1235U"
  },
  {
      "product_img": "https://m.media-amazon.com/images/I/61Kfqt-h5-L._SX679_.jpg",
      "product_name": "Dell Inspiron 3535, AMD Ryzen 3 7320U Processor",
      "brand": "Dell",
      "ram": 8,
      "Price": 29990,
      "description": "The Dell Inspiron 3535 features an AMD Ryzen 3 7320U processor and 8GB RAM, making it a cost-effective solution for everyday tasks and entertainment.",
      "storage": 512,
      "battery": 4100,
      "screen_size": 15.6,
      "operating_system": "Windows 11",
      "processor": "AMD Ryzen 3 7320U"
  },
  {
      "product_img": "https://m.media-amazon.com/images/I/71tSrDl1TaL._SX679_.jpg",
      "product_name": "Dell Inspiron 3530 Laptop, 13th Gen Intel Core i5-1334U Processor",
      "brand": "Dell",
      "ram": 16,
      "Price": 55155,
      "description": "The Dell Inspiron 3530 is a high-performance laptop equipped with a 13th Gen Intel Core i5-1334U processor and 16GB RAM. It's perfect for intensive tasks like programming and content creation.",
      "storage": 512,
      "battery": 4300,
      "screen_size": 15.6,
      "operating_system": "Windows 11",
      "processor": "Intel Core i5-1334U"
  },
  {
      "product_img": "https://m.media-amazon.com/images/I/71--62aSasL._SX679_.jpg",
      "product_name": "Dell Inspiron 3530 Thin & Light Laptop, 13th Gen Intel Core i3-1305U",
      "brand": "Dell",
      "ram": 8,
      "Price": 40149,
      "description": "The Dell Inspiron 3530 Thin & Light Laptop, powered by a 13th Gen Intel Core i3-1305U processor and 8GB RAM, delivers reliable performance in a compact form factor for students and professionals.",
      "storage": 512,
      "battery": 4200,
      "screen_size": 15.6,
      "operating_system": "Windows 11",
      "processor": "Intel Core i3-1305U"
  },
  {
      "product_img": "https://m.media-amazon.com/images/I/61gZoQw54-L._SX679_.jpg",
      "product_name": "Dell 15 Thin & Light Laptop, 12th Generation Intel Core i3-1215U Processor",
      "brand": "Dell",
      "ram": 8,
      "Price": 36490,
      "description": "The Dell 15 Thin & Light Laptop features a 12th Gen Intel Core i3-1215U processor and 8GB RAM, offering a perfect blend of performance and portability for daily computing tasks.",
      "storage": 512,
      "battery": 4200,
      "screen_size": 15.6,
      "operating_system": "Windows 11",
      "processor": "Intel Core i3-1215U"
  },
  {
      "product_img": "https://m.media-amazon.com/images/I/61fDHkQ6MqL._SX679_.jpg",
      "product_name": "Acer Aspire Lite 13th Gen Intel Core i3-1305U Thin and Light Premium Laptop",
      "brand": "Acer",
      "ram": 8,
      "Price": 31990,
      "description": "The Acer Aspire Lite is powered by a 13th Gen Intel Core i3-1305U processor and 8GB RAM, providing a premium experience in a sleek and lightweight design.",
      "storage": 512,
      "battery": 4000,
      "screen_size": 14,
      "operating_system": "Windows 11",
      "processor": "Intel Core i3-1305U"
  },
  {
      "product_img": "https://m.media-amazon.com/images/I/71czGb00k5L._SX522_.jpg",
      "product_name": "Acer Aspire Lite 12th Gen Intel Core i3-1215U Premium Metal Laptop",
      "brand": "Acer",
      "ram": 16,
      "Price": 30990,
      "description": "The Acer Aspire Lite with 12th Gen Intel Core i3-1215U processor and 16GB RAM combines high performance with a durable metal build, ideal for professionals and students alike.",
      "storage": 512,
      "battery": 4100,
      "screen_size": 15.6,
      "operating_system": "Windows 11",
      "processor": "Intel Core i3-1215U"
  },
  {
      "product_img": "https://m.media-amazon.com/images/I/61fDHkQ6MqL._SL1080_.jpg",
      "product_name": "Acer Aspire Lite AMD Ryzen 5-5625U",
      "brand": "Acer",
      "ram": 16,
      "Price": 34990,
      "description": "The Acer Aspire Lite with AMD Ryzen 5-5625U processor and 16GB RAM is designed for users needing speed and reliability, perfect for multitasking and productivity.",
      "storage": 512,
      "battery": 4500,
      "screen_size": 15.6,
      "operating_system": "Windows 11",
      "processor": "AMD Ryzen 5-5625U"
  },
  {
      "product_img": "https://m.media-amazon.com/images/I/618YKR-dBgL._SX679_.jpg",
      "product_name": "Acer Chromebook CB315-4H Intel Celeron N4500",
      "brand": "Acer",
      "ram": 8,
      "Price": 15990,
      "description": "The Acer Chromebook CB315-4H, powered by Intel Celeron N4500 processor and 8GB RAM, is an affordable and efficient choice for basic tasks and web browsing.",
      "storage": 64,
      "battery": 3800,
      "screen_size": 15.6,
      "operating_system": "Chrome OS",
      "processor": "Intel Celeron N4500"
  },
  {
      "product_img": "https://m.media-amazon.com/images/I/41Bmui2T3TL._SX300_SY300_QL70_FMwebp_.jpg",
      "product_name": "Acer Aspire Lite 13th Gen Intel Core i3-1305U",
      "brand": "Acer",
      "ram": 8,
      "Price": 31990,
      "description": "The Acer Aspire Lite features a 13th Gen Intel Core i3-1305U processor and 8GB RAM, offering a lightweight yet powerful laptop for everyday use.",
      "storage": 512,
      "battery": 4000,
      "screen_size": 14,
      "operating_system": "Windows 11",
      "processor": "Intel Core i3-1305U"
  }
];
